### ISSUE TITLE
Add advanced logging to the core

### ISSUE THREAD

**Issue by Woutwo** [yayscripting/YAY-Scripting-framework#15]
One thing this Framework needs is an advanced debugging/logging-option. Every major core-call (e.g. loading helper, loading class, loading other core-function) should be outputted when debugging mode is on. Sometimes one of the functions breaks and makes me start an adventure to the right file.

**Comment by yayscripting** [comment]
Whenever a function breaks and an exception is thrown there is a very extended stack trace. Did you consider using more exceptions in your code?

**Comment by Woutwo** [comment]
I just found out the problem is inside Smarty itself. It disables all kind of error_reporting and thus makes it very hard to find problems.
