### ISSUE TITLE
[JS] Placeholder

### ISSUE THREAD

**Issue by yayscripting** [yayscripting/YAY-Scripting-framework#2]
According to this topic:

http://www.banjomovies.nl/forum/index.php/topic,251.0.html

does placeholder.js not work properly.

**Comment by Djekkoo** [comment]
This issue has been solved. Only IE8 doesn't process the password-inputs well, but that is because of safety measures that seem to only exist in IE8, not 7 nor 9. I did do everything to keep it user-friendly on IE8.
