### ISSUE TITLE
SetMultiple not implented in forms.helpers

### ISSUE THREAD

**Issue by Woutwo** [yayscripting/YAY-Scripting-framework#6]
^ that. The ->setMultiple is not implented good; the Javascript is available but the backend is still missing; or atleast; it doesn't work.

`Call to undefined method HTML_Upload::setMultiple()`

**Comment by Djekkoo** [comment]
The function does exist according to my personal tests, and this file: https://github.com/yayscripting/YAY-Scripting-framework/blob/master/system/system/helpers/form.class.php#L1411-1428.

Could you try updating your system-dir, and if it still doesnt work send me your application folder to test?
